---
substitutions:
  id_prefix: ratgdo32
  friendly_name: "ratgdo32"
  uart_tx_pin: GPIO22
  uart_rx_pin: GPIO23
  input_obst_pin: GPIO3
  status_door_pin: GPIO15
  status_obstruction_pin: GPIO18
  dry_contact_open_pin: GPIO19
  dry_contact_close_pin: GPIO20
  dry_contact_light_pin: GPIO21

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  min_version: 2026.4.0
  project:
    name: ratgdo.v32board_secplus2
    version: "32.0"

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf
  variant: ESP32C6

status_led:
  pin: GPIO14

dashboard_import:
  package_import_url: github://zznyjidi/esphome-ratgdo-c6/v32board.yaml@main

packages:
  remote_package:
    url: https://github.com/zznyjidi/esphome-ratgdo-c6
    ref: main
    files: [base.yaml]
    refresh: 1s
  # remote_package: !include
  #   file: base.yaml

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s

web_server:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
    
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

logger:
